### ISSUE TITLE
Upload Failed Error - TypeError [ERR_INVALID_ARG_TYPE] 

### ISSUE THREAD

**Issue by themaxsmith** [gideo-llc/backblaze-b2-upload-any#3] opened 2021-06-30 05:18 UTC
I have started to see this error becoming very common using the uploadAny. Seems unrelated to what I am passing to it? Have loved the library for the past year. I can't figure out what in the library is breaking this

<img width="959" alt="Screen Shot 2021-06-30 at 12 12 39 AM" src="https://user-images.githubusercontent.com/19381797/123905788-92d8a680-d938-11eb-9a7d-d6718c19049b.png">

**Comment by cdhowie** [comment] 2021-07-01 04:56
What version of Node is this running on?  The optional `options` parameter to `https.request()` was added in Node 10.  I suspect you are trying to run this on an ancient and unsupported version of Node.

**Comment by themaxsmith** [comment] 2021-07-01 21:19
Running v14.15.5. I'll see if I can re-create it on a basic project and then share it with you. I'll PR if it's something in the library and I can figure it out.

**Comment by cdhowie** [comment] 2021-07-02 20:03
Re-evaluating the stack trace, this appears to be caused by monkey patching in the `agent-base` module.  Note the stack trace line directly above the highlighted one.  `agent-base` is intercepting the request and modifying it.  This dependency appears to be used by `cloudflare`.

This could be why you are only seeing the error in some cases -- perhaps only where you are using or activating this module?

Edit: Likely an old version of `agent-base` is in use.  Check this line from an old version of `agent-base.js`:

https://github.com/TooTallNate/node-agent-base/blob/66ddb62302f4585f1ca44810dc318c66a5410943/patch-core.js#L13

This is missing the `url` parameter, causing the URL to be passed as `options` and the options object to be passed as `cb`.  Then I'd expect to get the same error you are since `cb` is not a function.  I suspect that this version of this module was compatible with node 10, but not node 12+, which introduced a new (optional) parameter.

Assuming that this bug does not exist in the current version of `agent-base`, you should either upgrade to a version of `cloudflare` that does not depend on this old version, or file a bug report with the `cloudflare` module to update their dependencies.

For now I am going to close this issue since it seems to be caused by monkey-patching of node's standard library in a way that's incompatible with node 12+.

**Closed as completed** 2021-07-02 20:10 UTC
Labels: invalid
